#! /bin/sh
# pgrep -x sxhkd > /dev/null || sxhkd &

# feh --bg-center ~/Pictures/firewatch/illust_84655195_20201001_013416.jpg

# pgrep -x optimus-manager-qt ||  optimus-manager-qt
# picom 
# nm-applet
# xrandr --dpi 108 --output eDP-1

# pgrep -x polybar || polybar example

# bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d TERM BROWSER VIDEO IRC OTHER 
bspc monitor -d I II III IV V 

bspc config border_width         4
bspc config window_gap          10
bspc config top_padding          0
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc config focused_border_color "#88C0D0"
bspc config normal_border_color "#e6eef3"
bspc config active_border_color "#eceff4"
bspc config presel_feedback_color "#98C379"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a vlc desktop='^3' follow=on
bspc rule -a tim.exe desktop='^4' follow=on  
bspc rule -a Wine desktop='^4'  follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bash /home/daoist/dotfiles/bspwm/launch.sh
